# How to run container: docker-compose up -d --build
services:
  web:
    container_name: web6
    environment:
      - FLAG=${FLAG}
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - web6:latest
    image: web6:latest
    ports:
      - "80:4444" # hosts 80 forwards to dockers 4444
    restart: unless-stopped