# How to run container: docker-compose up -d --build
services:
  web:
    container_name: web5
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - web5:latest
    image: web5:latest
    ports:
      - "80:8080" # hosts 80 forwards to dockers 8080
    restart: unless-stopped