# How to run container: docker-compose up -d --build
services:
  web:
    container_name: web5
    environment:
      - FLAG=${FLAG}
    build:
      context: .
      dockerfile: Dockerfile
    image: web5:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.khi.rule=Host(`web5.ctf.hacksu.com`)"
      - "traefik.http.routers.khi.entrypoints=websecure"
      - "traefik.http.routers.khi.tls.certresolver=letsencrypt"
      - "traefik.http.services.khi.loadbalancer.server.port=8080"
    restart: unless-stopped