# How to run container: docker-compose up -d --build
services:
  handler:
    container_name: handler
    build:
      context: .
      dockerfile: Dockerfile
    image: handler:latest
    ports:
      - "2540:2540"
      - "2541:2541"
      - "2542:2542"
      - "2543:2543"
      - "2544:2544"
    restart: unless-stopped