# How to run container: docker-compose up -d --build
services:
  web:
    container_name: web4
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - web4:latest
    image: web4:latest
    ports:
      - "80:4444" # hosts 80 forwards to dockers 4444
    restart: unless-stopped